### PR TITLE
feat: Cycle Warning Command

### PR DESCRIPTION
**Pull request by ko-zone**
## Description
Added command for nav data warnings regarding cycle

## Test Results

image

## Discord Username

KO#2134

### CODE REVIEW

**Comment by nakajimayoshi** [comment]
@ko-zone Looks great! As Come mentioned I think we can get rid of the simbrief AIRAC point, as the dmc doesn't care about the simbrief AIRAC used. And instead of "several" reasons, "couple of reasons". 

Also in the index.ts file please put the new command at the bottom of the list, and for the commands index make sure it's in alphabetical order. Thanks

**Comment by ko-zone** [comment]
image

Looks like this at the minute.

**Review by nakajimayoshi — APPROVED** [review]
LGTM!

**Review by nakajimayoshi — CHANGES_REQUESTED** [review]
Add your changes to the changelog!

**Review by nakajimayoshi — APPROVED** [review]

**Pull request merged**
